apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: order
  name: order
spec:
  ports:
  - name: 8161-8161
    port: 8161
    protocol: TCP
    targetPort: 8161
  selector:
    app: order
  type: ClusterIP
status:
  loadBalancer: {}
